spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3307/railwaysMySQL
    username: root
    password: prisma
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      generate-ddl: true
      show-sql: true
  rabbitmq:
    port: 5672
    username: guest
    password: guest

server:
  port: 8081
  error:
    include-stacktrace: never
