version: '3.1'
services:
  mysql-db:
    container_name: railwaysMySQL
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - C:\Users\Matteo.Sottosanti\IdeaProjects\Uniprisma\mysqlDatabases\Exercise5.2
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: railwaysMySQL